/// Flutter icons IconsX
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconsX
///      fonts:
///       - asset: fonts/IconsX.ttf
///
/// 
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Brandico, (C) 2012 by Vitaly Puzrin
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
library icons_x;

import 'package:flutter/widgets.dart';

class IconsX {
  IconsX._();

  static const _kFontFam = 'IconsX';

  static const IconData home_1 = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData home_circled = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData search = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData search_circled = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData search_1 = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData search_2 = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData search_3 = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData user_outline = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData user = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData user_1 = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData user_woman = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData params = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData wrench = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData wrench_outline = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData info = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData help_circled = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData question = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData eye_1 = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData eye_off = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData right_dir = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData left_dir = IconData(0xe814, fontFamily: _kFontFam);
  static const IconData down_dir = IconData(0xe815, fontFamily: _kFontFam);
  static const IconData up_dir = IconData(0xe816, fontFamily: _kFontFam);
  static const IconData left_open_outline = IconData(0xe817, fontFamily: _kFontFam);
  static const IconData left_open = IconData(0xe818, fontFamily: _kFontFam);
  static const IconData right_open_outline = IconData(0xe819, fontFamily: _kFontFam);
  static const IconData right_open = IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData users = IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData users_1 = IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData sort_alphabet = IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData chart_line = IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData comment_inv = IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData comment = IconData(0xe820, fontFamily: _kFontFam);
  static const IconData chat = IconData(0xe821, fontFamily: _kFontFam);
  static const IconData credit_card = IconData(0xe822, fontFamily: _kFontFam);
  static const IconData github_text = IconData(0xe823, fontFamily: _kFontFam);
  static const IconData logout = IconData(0xe824, fontFamily: _kFontFam);
  static const IconData cloud_sun = IconData(0xe825, fontFamily: _kFontFam);
  static const IconData bug_report = IconData(0xe826, fontFamily: _kFontFam);
  static const IconData report = IconData(0xe827, fontFamily: _kFontFam);
  static const IconData report_problem = IconData(0xe828, fontFamily: _kFontFam);
  static const IconData attention = IconData(0xe829, fontFamily: _kFontFam);
  static const IconData warning_empty = IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData font = IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData pencil = IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData floppy = IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData ok_outline = IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData ok = IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData wifi_outline = IconData(0xe830, fontFamily: _kFontFam);
  static const IconData github = IconData(0xf113, fontFamily: _kFontFam);
  static const IconData location_arrow = IconData(0xf124, fontFamily: _kFontFam);
  static const IconData instagram = IconData(0xf16d, fontFamily: _kFontFam);
  static const IconData android = IconData(0xf17b, fontFamily: _kFontFam);
  static const IconData moon = IconData(0xf186, fontFamily: _kFontFam);
  static const IconData slack = IconData(0xf198, fontFamily: _kFontFam);
  static const IconData reddit_alien = IconData(0xf281, fontFamily: _kFontFam);
  static const IconData twitter = IconData(0xf302, fontFamily: _kFontFam);
  static const IconData versions = IconData(0xf310, fontFamily: _kFontFam);
  static const IconData graph = IconData(0xf35a, fontFamily: _kFontFam);
  static const IconData home = IconData(0xf35f, fontFamily: _kFontFam);
  static const IconData eye_closed = IconData(0xf366, fontFamily: _kFontFam);
  static const IconData facebook_f = IconData(0xf39e, fontFamily: _kFontFam);
  static const IconData facebook_messenger = IconData(0xf39f, fontFamily: _kFontFam);
  static const IconData eye_2 = IconData(0xf3a8, fontFamily: _kFontFam);
  static const IconData info_1 = IconData(0xf3a9, fontFamily: _kFontFam);
  static const IconData search_location = IconData(0xf689, fontFamily: _kFontFam);
  static const IconData cloud_moon = IconData(0xf6c3, fontFamily: _kFontFam);
  static const IconData menu_outline = IconData(0xe831, fontFamily: _kFontFam);
}
